spring:
  data:
    mongodb:
      uri: mongodb+srv://tcsemp:KGDYtY7becFPJkRw@tcsemp.uocygyg.mongodb.net/?retryWrites=true&w=majority
      database: tcsemp
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


server:
  port: 8080
mongock:
  enabled: true
  migration-scan-package:
    - com.tcs.mongo
  runner-type: applicationrunner
